sevia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
from sevia_app import views as sevia_views


admin.site.site_header = 'SEVIA Admin'
admin.site.index_title= 'SEVIA Admin Dashboard' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sevia_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('accounts.api.urls')),
    path('api/sevia/', include('sevia_app.api.urls')),
    path('privacy-policy/', sevia_views.privacy_policy, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sevia_app/urls.py
from django.urls import path
from sevia_app import views
from sevia_app.api import views as api_views

app_name = 'sevia_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('users/', views.users, name='users'),
    path('facilities/', views.FacilityListView.as_view(), name='facility_list'),
    path('facility/', views.FacilityCreateView.as_view(), name='facility_create'),
    path('facility/update/<int:pk>/', views.FacilityUpdateView.as_view(), name='facility_update'),
    path('facility/delete/<int:pk>/', views.FacilityDeleteView.as_view(), name='facility_delete'),
    path('facility/detail/<int:pk>/', views.FacilityDetailView.as_view(), name='facility_detail'),
    path('patients/', views.PatientListView.as_view(), name='patient_list'),
    path('patient', views.PatientCreateView.as_view(), name='patient_create'),
    path('patient/update/<int:pk>/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('patient/delete/<int:pk>/', views.PatientDeleteView.as_view(), name='patient_delete'),
    path('patient/detail/<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('countries/', views.CountryListView.as_view(), name='country_list'),
    path('country', views.CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', views.CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', views.CountryDeleteView.as_view(), name='country_delete'),
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('region/', views.RegionCreateView.as_view(), name='region_create'),
    path('region/update/<int:pk>/', views.RegionUpdateView.as_view(), name='region_update'),
    path('region/delete/<int:pk>/', views.RegionDeleteView.as_view(), name='region_delete'),
    path('districts/', views.DistrictListView.as_view(), name='district_list'),
    path('district/', views.DistrictCreateView.as_view(), name='district_create'),
    path('district/update/<int:pk>/', views.DistrictUpdateView.as_view(), name='district_update'),
    path('district/delete/<int:pk>/', views.DistrictDeleteView.as_view(), name='district_delete'),
    path('patient_datas/', views.PatientDataListView.as_view(), name='patient_data_list'),
    path('patient_data/', views.PatientDataCreateView.as_view(), name='patient_data_create'),
    path('patient_data/update/<slug:pk>/', views.PatientDataUpdateView.as_view(), name='patient_data_update'),
    path('patient_data/delete/<slug:pk>/', views.PatientDataDeleteView.as_view(), name='patient_data_delete'),
    path('reviewer_datas/', views.ReviewerDataListView.as_view(), name='reviewer_data_list'),
    path('reviewer_data/<slug:patient_data_uri>', views.ReviewerDataCreateView.as_view(), name='reviewer_data_create'),
    path('reviewer_data/update/<slug:pk>/', views.ReviewerDataUpdateView.as_view(), name='reviewer_data_update'),
    path('reviewer_data/delete/<slug:pk>/', views.ReviewerDataDeleteView.as_view(), name='reviewer_data_delete'),
    path('settings/', views.settings, name='settings'),
    path('report/', views.ReportView.as_view(), name='reports'),
    path('api/app-dashboard', api_views.app_dash, name='app-dash'),
]

tutorial/urls.py
from django.urls import path
from tutorial import views

app_name = 'tutorial'
urlpatterns = [
    path('', views.TutorialListIndexView.as_view(), name='tutorial_index'),
    path('tutorial/view/<slug:pk>/', views.TutorialDetailView.as_view(), name='tutorial'),
    path('tutorials/', views.TutorialListView.as_view(), name='tutorial_list'),
    path('tutorial/', views.TutorialCreateView.as_view(), name='tutorial_create'),
    path('tutorial/update/<slug:pk>/', views.TutorialUpdateView.as_view(), name='tutorial_update'),
    path('tutorial/delete/<slug:pk>/', views.TutorialDeleteView.as_view(), name='tutorial_delete'),
]

tutorial/models.py
from django.db import models
from accounts.models import User


class Tutorial(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User,on_delete=models.PROTECT,)
    title = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_first_image(self):   
        if self.tutorialmediafiles_set.exclude(tutorial_image = None).count():
            return self.tutorialmediafiles_set.all()[0].tutorial_image

class TutorialMediaFiles(models.Model):
    tutorial = models.ForeignKey(Tutorial,on_delete=models.PROTECT,)
    tutorial_image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True, null=True,default=None)
    tutorial_file = models.FileField(upload_to='tutorial_files/%Y/%m/%d',blank=True, null=True,default=None)
    video_url = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = " Tutorial Media Files"

    def __str__(self):
        return str(self.tutorial)

tutorial/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from tutorial.models import Tutorial

class TutorialListIndexView(LoginRequiredMixin, generic.ListView):
    template_name ='tutorial/tutorial_list_index.html'
    def get_queryset(self):
        return Tutorial.objects.all()

class TutorialDetailView(LoginRequiredMixin, generic.DetailView):
    template_name ='tutorial/tutorial_detail.html'
    context_object_name = 'tutorial'
    queryset = Tutorial.objects.all()

class TutorialListView(LoginRequiredMixin, generic.ListView):
    template_name ='tutorial/tutorial_list.html'
    def get_queryset(self):
        return Tutorial.objects.all()

class TutorialCreateView(LoginRequiredMixin, generic.CreateView):
    template_name ='tutorial/tutorial_create_form.html'
    model = Tutorial
    fields = "__all__"
    success_url = reverse_lazy('tutorial:tutorial_create')

class TutorialUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name ='tutorial/tutorial_update_form.html'
    model = Tutorial
    fields = "__all__"
    success_url = reverse_lazy('tutorial:tutorial_list')



class TutorialDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name ='tutorial/tutorial_delete_form.html'
    model = Tutorial
    success_url = reverse_lazy('tutorial:tutorial_list')

tutorial/templates/tutorial/tutorial_create_form.html
{% extends "sevia_app/base.html" %} {% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 500px">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">New Region</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

{% endblock extra_styles %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script language="javascript">
  $(document).ready(function () {
    $(".selectmultiple , .select").select2();
  });
</script>

{% endblock extra_js %}

tutorial/templates/tutorial/tutorial_delete_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="post">{% csrf_token %}
         <legend class="border-bottom mb-4">Delete Region</legend>
            <p>Are you sure you want to delete region with id <b>"{{ object }}"</b> ?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'sevia_app:facility_list' %}" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
{% endblock content %}

tutorial/templates/tutorial/tutorial_detail.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>{{ tutorial.title}}</h1>
<div class="card">
  <div class="card-body">
  <h3>Description:</h3>
    <p class="card-text" style="font-weight: 500">
          {{ tutorial.description}}
    </p>

    <h3>Resources:</h3>
    {% for media in tutorial.tutorialmediafiles_set.all %}
    {% if media.tutorial_image %}
    <p>Image : <a href="{{ media.tutorial_image.url }}" target="_blank">{{ media.tutorial_image.name }}</a></p>
    {% endif %}
    {% if media.tutorial_file %}
    <p>File : <a href="{{ media.tutorial_file.url }}" target="_blank">{{ media.tutorial_file.name }}</a></p>
    {% endif %}
    {% if media.video_url %}
    <p>Video : <a href="{{ media.video_url }}" target="_blank">{{ media.video_url }}</a></p>
    {% endif %}
    {% endfor %}


    <footer class="blockquote-footer h4">Prepared By <cite title="Source Title">{{ tutorial.creator.fullname }}</cite></footer>


  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>

{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

<script language="javascript">
  $(document).ready(function () {
    $("#facilities_table").DataTable({
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

tutorial/templates/tutorial/tutorial_list.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>Tutorials</h1>
<div class="card">
  <div class="card-body">
    <table class="table table-striped table-bordered" id="facilities_table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">Creator</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {%for tutorial in tutorial_list %}
        <tr>
          <th scope="row">{{ tutorial.id}}</th>
          <td>{{ tutorial.title}}</td>
          <td>{{ tutorial.description}}</td>
          <td>{{ tutorial.creator}}</td>
          <td>
            <a
              role="button"
              href="{% url 'tutorial:tutorial_update' tutorial.id %}"
              class="btn btn-pure btn-primary icon md-edit"
            ></a>
            <a
              role="button"
              href="{% url 'tutorial:tutorial_delete' tutorial.id %}"
              class="btn btn-pure btn-danger icon md-delete"
            ></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>

{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

<script language="javascript">
  $(document).ready(function () {
    $("#facilities_table").DataTable({
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

tutorial/templates/tutorial/tutorial_list_index.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>Topics</h1>
<div class="row">  
{%for tutorial in tutorial_list %}
<div class="col-md-4">
<div class="card">
  {% if tutorial.get_first_image %}
  <img class="card-img-top" style="max-height: 150px;" src="{{ tutorial.get_first_image.url }}" alt="Topic Image">

  {% endif %}
  <div class="card-body">
    <h3 class="card-title">{{ tutorial.title}}</h3>
    <p class="card-text" style="display: -webkit-box;
    -webkit-line-clamp: 4;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-overflow: ellipsis;">
          {{ tutorial.description}}
    </p>
    <footer class="blockquote-footer h4">Prepared By <cite title="Source Title">{{ tutorial.creator.fullname }}</cite></footer>

      <a href="{% url 'tutorial:tutorial' tutorial.id%}" class="btn btn-primary">Read More</a>

  </div>
</div>
</div>
{% endfor %}
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>

{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

<script language="javascript">
  $(document).ready(function () {
    $("#facilities_table").DataTable({
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

tutorial/templates/tutorial/tutorial_update_form.html
{% extends "sevia_app/base.html" %} {% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 500px">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update Region</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
          <a
            href="{% url 'sevia_app:region_list' %}"
            class="btn btn-outline-info"
            >Cancel</a
          >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

{% endblock extra_styles %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script language="javascript">
  $(document).ready(function () {
    $(".selectmultiple , .select").select2();
  });
</script>

{% endblock extra_js %}