accounts/api/urls.py
from django.urls import path,include
from accounts.api.views import UserViewSet,GetAuthToken
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('accounts/login/', GetAuthToken.as_view())
]

accounts/urls.py
from django.urls import path,include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', views.Maintainance, name='login'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    template_name="accounts/password_reset_confirm.html",success_url = reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    path('logout/', views.Logout, name="logout"),
    path('register', views.UserRegisterView.as_view(), name='user_register'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('user', views.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('user/detail/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('user/delete/<int:pk>', views.UserDeleteView.as_view(), name='user_delete'),
    path('user/profile/', views.profile, name='profile'),
]

sevia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
from sevia_app import views as sevia_views


admin.site.site_header = 'SEVIA Admin'
admin.site.index_title= 'SEVIA Admin Dashboard' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sevia_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('accounts.api.urls')),
    path('api/sevia/', include('sevia_app.api.urls')),
    path('privacy-policy/', sevia_views.privacy_policy, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sevia_app/models.py
from django.db import models
from accounts.models import User
import datetime
from django.utils.translation import ugettext_lazy as _
import uuid
from django.contrib.auth.models import Group
from django.contrib.postgres.fields import JSONField


ASSESSMENT_CHOICES = [
        ('VIA neg','VIA Negative No treatment'),
        ('VIA+ for cryotherapy','VIA Positive for cryotherapy/Thermal Cagulation'),
        ('VIA+ LEEP','VIA Positive LEEP'),
        ('VIA+ refer LEEP','VIA Positive Refer ForLEEP'),
        ('Suspect Cancer','Suspect For Cancer Take Punch Biopsy'),
        ('Cervicitis Give Antibiotics','Cervicitis Give Antibiotics'),
        ('Cervical Polyp','Cervical Polyp (Refer / Do Polypectomy)'),
        ('Others','Others')
        ]

class Country(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)

    class Meta:
        verbose_name_plural = "Countries"
    
    def __str__(self):
        return self.name

class Region(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)
    country = models.ForeignKey(Country,on_delete=models.PROTECT,)

    
    def __str__(self):
        return self.name

class District(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)
    region = models.ForeignKey(Region,on_delete=models.PROTECT,)

    
    def __str__(self):
        return self.name

class FacilityGroupDetail(models.Model):
    id = models.AutoField(primary_key=True)
    group_name = models.CharField(max_length=100, blank=True)
    users = models.ManyToManyField(User)
    def __str__(self):
        return self.group_name

class Facility(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=30, blank=True,null=True)
    district = models.ForeignKey(District,on_delete=models.PROTECT,)
    facility_group = models.ForeignKey(FacilityGroupDetail,on_delete=models.PROTECT,)
    name = models.CharField(max_length=60, blank=True)
    phone = models.CharField(max_length=60, null=True,blank=True)
    users = models.ManyToManyField(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        verbose_name_plural = "Facilities"
    
    def __str__(self):
        return self.name

    def get_full_address(self):
        return self.district.name + ' , ' + self.district.region.name



class Form(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField(null=True,blank=True,default=None)
    country_id = models.ForeignKey(Country, on_delete=models.PROTECT,null=True,blank=True)
    group = models.ForeignKey(Group,on_delete=models.PROTECT,null=True,blank=True,default=None)
    table_name = models.CharField(max_length=30)
    table_def = models.TextField(null=True,blank=True,default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.table_name

class FormData(models.Model):
    uri = models.CharField(primary_key=True,max_length=64,default=uuid.uuid4)
    form_id = models.ForeignKey(Form,on_delete=models.PROTECT,)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT,)
    exported = models.BooleanField(default=0)
    exported_at = models.DateTimeField(blank=True,default=None,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    data = JSONField(null=True)

    def __str__(self):
        return self.uri

class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(verbose_name='First Name',max_length=30,blank=True,null=True,default=None)
    middle_name = models.CharField(verbose_name='Middle Name',max_length=30,blank=True,null=True,default=None)
    last_name = models.CharField(verbose_name='Sur Name',max_length=30,blank=True,null=True,default=None)
    phone = models.CharField(verbose_name='phonenumber',max_length=30,null=True, blank=True)
    age = models.CharField(verbose_name='age',max_length=30,null=True, blank=True)
    facility = models.ManyToManyField(Facility)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,null=True, blank=True)

    def __str__(self):
        return str(self.id)

    def get_full_name(self):
        first_name = self.first_name if self.first_name else '' 
        middle_name = self.middle_name if self.middle_name else '' 
        last_name = self.last_name if self.last_name else '' 
        fullname = self.first_name + ' ' + middle_name +' ' + last_name
        return str(fullname)


class FormPatientDataV1(models.Model):

    PITC_CHOICES = [('No','No'),('Yes','Yes')]
    HIV_CHOICES = [('Positive','Positive'),('Negative','Negative'),('Unknown','Unknown')]
    VISIT_CHOICES = [
        ('New client (nevwer been screened)','New client (nevwer been screened)'),
        ('Postponed cryotherapy','Postponed cryotherapy'),
        ('Post-treatment complication (Cryo or LEEP)','Post-treatment complication (Cryo or LEEP)'),
        ('LEEP','LEEP'),
        ('1 year follow-up VIA+ (VIA+ treated with Cryo or LEEP)','1 year follow-up VIA+ (VIA+ treated with Cryo or LEEP)'),
        ('Routine VIA screening (returning client previously VIA-)','Routine VIA screening (returning client previously VIA-)'),
        ('Referred for VIA+ client(reffered for cryo)','Referred for VIA+ client(reffered for cryo)'),
        ('Referred for suspect cancer','Referred for suspect cancer'),
        ('Post-cryotherapy images','Post-cryotherapy images'),
        ]
    

    uri = models.CharField(max_length=64,primary_key=True,unique=True,default=uuid.uuid4)
    patient = models.ForeignKey(Patient,on_delete=models.PROTECT,)
    provider = models.ForeignKey(User,on_delete=models.PROTECT,related_name="provider")
    ccs_providers_full_name = models.CharField(max_length=128,blank=True, null=True)
    ccs_providers_phone_no = models.CharField(max_length=128,blank=True, null=True)
    screen_date = models.DateField(default=datetime.date.today)
    parity = models.BigIntegerField(blank=True, null=True)
    patient_received_pitc = models.CharField(max_length=128,default=None,blank=True, null=True,choices=PITC_CHOICES,)
    ccs_facility_no = models.CharField(max_length=128,blank=True, null=True)
    ccs_no = models.CharField(max_length=128,blank=True, null=True)
    hiv_status = models.CharField(max_length=128,default=None,blank=True, null=True,choices=HIV_CHOICES,)
    assessment = models.CharField(max_length=128,default=None,blank=True, null=True,choices=ASSESSMENT_CHOICES,)
    visit_status = models.CharField(max_length=128,default=None,blank=True, null=True, choices=VISIT_CHOICES,)
    photo_1 = models.ImageField(upload_to='patient_data/%Y/%m/%d',blank=True, null=True)
    photo_2 = models.ImageField(upload_to='patient_data/%Y/%m/%d', blank=True, null=True)
    photo_3 = models.ImageField(upload_to='patient_data/%Y/%m/%d', blank=True, null=True)
    form_version = models.CharField(max_length=128,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.uri)

    class Meta:
        # managed = False
        db_table = '_form_patient_data_v1'

class FormReviewerDataV1(models.Model):
    uri = models.CharField(max_length=64,primary_key=True,default=uuid.uuid4)
    patient_data = models.OneToOneField(FormPatientDataV1, to_field="uri",on_delete=models.PROTECT,related_name="reviewer_data",db_constraint=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name="creator",db_constraint=False)
    assessment = models.CharField(max_length=128, blank=True, null=True,choices=ASSESSMENT_CHOICES,)
    comment = models.CharField(max_length=128, blank=True, null=True)
    mismatch = models.IntegerField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


    def __str__(self):
        return str(self.uri)
        
    class Meta:
        # managed = False
        db_table = '_form_reviewer_data_v1'


class DataDictionary(models.Model):
    formId = models.TextField(null=True,blank=True,default=None)
    formVersion = models.TextField(null=True,blank=True,default=None)
    variableKey= models.TextField(null=True,blank=True,default=None)
    variableName = models.TextField(null=True,blank=True,default=None)
    description = models.TextField(null=True,blank=True,default=None)
    status = models.IntegerField(blank=True, null=True,default=0)

    
    def __str__(self):
        return self.formId

class FormPatientDataV2(models.Model):

    HIV_CHOICES = [('Positive','Positive'),('Negative','Negative'),('Unknown','Unknown')]
    
    uri = models.CharField(max_length=64,primary_key=True,unique=True,default=uuid.uuid4)
    patient = models.ForeignKey(Patient,on_delete=models.PROTECT,)
    provider = models.ForeignKey(User,on_delete=models.PROTECT)
    visit_date = models.DateField(default=datetime.date.today)
    visit_status = models.CharField(max_length=128,default=None,blank=True, null=True)
    first_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    middle_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    last_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    phone = models.CharField(max_length=30,blank=True,null=True,default=None)
    age = models.IntegerField(blank=True, null=True)
    passport = models.CharField(max_length=30,blank=True,null=True,default=None)
    followup_reasons = models.CharField(max_length=128,default=None,blank=True, null=True)

accounts/api/views.py
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from accounts.api.serializer import UserSerializer,GroupSerializer
from accounts.models import User
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from sevia_app.api.serializer import SimplifiedFacilitySerializer,CountrySerializer
from sevia_app.models import Country,Facility
from rest_framework.permissions import IsAuthenticated


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-created_on')
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated]


class GetAuthToken(ObtainAuthToken,APIView):

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        groups_serializer = GroupSerializer(user.groups.all(), many=True)
        facility_serializer = SimplifiedFacilitySerializer(user.facility_set.all(), many=True)
        country_serializer = CountrySerializer(Country.objects.filter(region__district__facility__in=Facility.objects.filter(users=user).all()), many=True)
        return Response({
            'token': token.key,
            'user_id': user.id,
            'username': user.username,
            'fullname':user.fullname,
            'email': user.email,
            'phonenumber':user.phone,
            'active':user.active,
            'admin':user.admin,
            'created_on':user.created_on,
            'updated_at':user.updated_at,
            'roles':groups_serializer.data,
            'facilities':facility_serializer.data,
            'countries':country_serializer.data,
        })

accounts/templates/accounts/login.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}       
          <div class="brand hidden-md-up">
            <img class="brand-img" width="40px" src="{% static 'sevia_app/assets/images/sevia_nobg.png' %}" alt="...">
            <h3 class="brand-text font-size-40">SEVIA</h3>
          </div>
          <h3 class="font-size-24">Sign In</h3>
          <p>Delighted to have you</p>

          <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign In</button>

                <a href="{% url 'accounts:password_reset'%}" class="mx-10">Forgot password</a>
                <p></p>
                <p>No account?<a href="{% url 'accounts:user_register'%}" class="mx-3">Sign Up</a></p>                
            </div>
        </form>
{% endblock content %}

accounts/templates/accounts/maintainance.html
{% extends "accounts/auth_layout.html" %}
{% load static %}
{% block content %}
<div class="page-content vertical-align-middle">
  <i style="font-size: 55px;" class="icon md-settings icon-spin page-maintenance-icon" aria-hidden="true"></i>
  <p style="font-size: 55px;">Under Maintenance</p>
  <p>PLEASE GIVE US A MOMENT TO SORT THINGS OUT</p>

  <footer class="page-copyright">
    <p>WEBSITE BY SkyConnect</p>
    <p>© 2021. All RIGHT RESERVED.</p>
    <div class="social">
      <a class="btn btn-icon btn-pure" href="javascript:void(0)">
    <i class="icon bd-twitter" aria-hidden="true"></i>
  </a>
      <a class="btn btn-icon btn-pure" href="javascript:void(0)">
    <i class="icon bd-facebook" aria-hidden="true"></i>
  </a>
      <a class="btn btn-icon btn-pure" href="javascript:void(0)">
    <i class="icon bd-google-plus" aria-hidden="true"></i>
  </a>
    </div>
  </footer>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
          <div class="brand hidden-md-up">
            <img class="brand-img" width="40px" src="{% static 'sevia_app/assets/images/sevia_nobg.png' %}" alt="...">
            <h3 class="brand-text font-size-40">SEVIA</h3>
          </div>
          <h3 class="font-size-24">Reset Password</h3>
          <p>Forgotten your password? <br/> Enter your email address below, and we'll email instructions for setting a new one.</p>

          <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
            <p></p>
            <a href="{% url 'accounts:login'%}" class="mx-0">Return back to Login</a>
        </form>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
          <div class="brand hidden-md-up">
            <img class="brand-img" width="40px" src="{% static 'sevia_app/assets/images/sevia_nobg.png' %}" alt="...">
            <h3 class="brand-text font-size-40">SEVIA</h3>
          </div>
          <h3 class="font-size-24">Password reset complete</h3>
          <p>Your password has been set. You may go ahead and log in now.</p>

          <a href="{% url 'accounts:login'%}" class="btn btn-primary">Log in</a>

{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
          <div class="brand hidden-md-up">
            <img class="brand-img" width="40px" src="{% static 'sevia_app/assets/images/sevia_nobg.png' %}" alt="...">
            <h3 class="brand-text font-size-40">SEVIA</h3>
          </div>
          <h3 class="font-size-24">Password Reset Confirm</h3>
          <p>Please enter your new password</p>

          <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>

{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
          <div class="brand hidden-md-up">
            <img class="brand-img" width="40px" src="{% static 'sevia_app/assets/images/sevia_nobg.png' %}" alt="...">
            <h3 class="brand-text font-size-40">SEVIA</h3>
          </div>
          <h3 class="font-size-24">Password reset sent</h3>
          <p>We've emailed you instructions for setting your password, <br />
             If an account exists with the email you entered. You should receive them shortly.<br />
             If you don't receive an email, please make sure you've entered the address you registered with, <br/>
              and check your spam folder.</p>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">NEW USER</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/user_create_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 500px">
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New User</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>
        </div>
    </div>
  </div>
{% endblock content %}

{% block extra_styles %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />


{% endblock extra_styles %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script language="javascript">
  
        $(document).ready(function() {
            $('.selectmultiple , .select').select2();
        });

    </script>

{% endblock extra_js %}

accounts/templates/accounts/user_delete_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="post">{% csrf_token %}
         <legend class="border-bottom mb-4">Delete User</legend>
            <p>Are you sure you want to delete <b>"{{ object }}"</b> ?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'accounts:user_list' %}" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/user_list.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>Users</h1>
<div class="card">
  <div class="card-body">
    <table class="table table-striped table-bordered" id="users_table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Username</th>
          <th scope="col">Name</th>
          <th scope="col">Phone</th>
          <th scope="col">Roles</th>
          <th scope="col">Facilities</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {%for user in user_list %}
        <tr>
          <th scope="row">{{user.id}}</th>
          <td>{{user.username}}</td>
          <td>{{user.fullname}}</td>
          <td>{{user.phone}}</td>
          <td>
          {%for g in user.groups.all %}
            {{g.name}} {% if not forloop.last %}, {% endif %}
          {%endfor%}
          </td>
          <td>
            {%for f in user.facility_set.all %}
              {{f.name}} {% if not forloop.last %}, {% endif %}
            {%endfor%}
          </td>
          <td>
            <a
              role="button"
              href="{% url 'accounts:user_update' user.id %}"
              class="btn btn-pure btn-primary icon md-edit"
            ></a>
            <a
              role="button"
              href="{% url 'accounts:user_detail' user.id %}"
              class="btn btn-pure btn-info icon md-eye"
            ></a>
            <a
              role="button"
              href="{% url 'accounts:user_delete' user.id %}"
              class="btn btn-pure btn-danger icon md-delete"
            ></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/fixedheader/3.1.8/css/fixedHeader.bootstrap.min.css"
/>
<style>
  div.dataTables_wrapper {
        margin: 0 auto;
    }
    thead input {
        width: 100%;
    }
    td {
        width: 1000px;
    }

    table{
  margin: 0 auto;
  width: 100%;
  clear: both;
  border-collapse: collapse;
  table-layout: fixed; 
  word-wrap:break-word;
}
</style>


{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.8/js/dataTables.fixedHeader.min.js"></script>


<script language="javascript">
  $(document).ready(function () {
    $("#users_table").DataTable({
      scrollX: true,
      fixedHeader: true,
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

accounts/templates/accounts/user_register_form.html
{% extends "accounts/auth_layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}   
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Register</button>
            </div>
        </form>
  {% endblock content %}

accounts/templates/accounts/user_update_form.html
{% extends "sevia_app/base.html" %} {% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 700px">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update User</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
          <a href="{% url 'accounts:user_list' %}" class="btn btn-outline-info"
            >Cancel</a
          >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

{% endblock extra_styles %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script language="javascript">
  $(document).ready(function () {
    $(".selectmultiple , .select").select2();
  });
</script>

{% endblock extra_js %}