accounts/urls.py
from django.urls import path,include,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', views.Maintainance, name='login'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    template_name="accounts/password_reset_confirm.html",success_url = reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html'), name='password_reset_done'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    path('logout/', views.Logout, name="logout"),
    path('register', views.UserRegisterView.as_view(), name='user_register'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('user', views.UserCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('user/detail/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('user/delete/<int:pk>', views.UserDeleteView.as_view(), name='user_delete'),
    path('user/profile/', views.profile, name='profile'),
]

sevia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
from sevia_app import views as sevia_views


admin.site.site_header = 'SEVIA Admin'
admin.site.index_title= 'SEVIA Admin Dashboard' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sevia_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('accounts.api.urls')),
    path('api/sevia/', include('sevia_app.api.urls')),
    path('privacy-policy/', sevia_views.privacy_policy, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sevia_app/api/urls.py
from django.urls import path,include
from sevia_app.api import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'country', views.CountryViewSet)
router.register(r'region', views.RegionViewSet)
router.register(r'district', views.DistrictViewSet)
router.register(r'facility', views.FacilityViewSet)
router.register(r'facility_group', views.FacilityGroupDetailViewSet)
router.register(r'form', views.FormViewSet)
router.register(r'form_data', views.FormDataViewSet)
router.register(r'form_patient_data', views.FormPatientDataV1ViewSet)
router.register(r'form_reviewer_data', views.FormReviewerDataV1ViewSet)
router.register(r'patient', views.PatientViewSet)
router.register(r'form_patient_data_v2', views.FormPatientDataV2ViewSet)

urlpatterns = [
    path('user/forms/<int:pk>/', views.userforms, name="user_forms"),
    path('form_patient_data/unreviewed/', views.form_patient_data_unreviewed, name="form_patient_data_unreviewed"),
    path('provider_reviewed/<int:pk>/', views.get_provider_reviewed_cases, name='provider_reviewed'),
    path('provider_unreviewed/<int:pk>/', views.get_provider_unreviewed_cases, name='provider_unreviewed'),
    path('provider_mismatch/<int:pk>/', views.get_provider_mismatch_cases, name='provider_mismatch'),
    path('reviewer_reviewed/<int:pk>/', views.get_reviewer_reviewed_cases, name='reviewer_reviewed'),
    path('reviewer_unreviewed/<int:pk>/', views.get_reviewer_unreviewed_cases, name='reviewer_unreviewed'),
    path('reviewer_mismatch/<int:pk>/', views.get_reviewer_mismatch_cases, name='reviewer_mismatch'),
    path('case_data_json/<str:pk>/', views.get_case_data_json, name='case_data_json'),
    path('test', views.test, name="test"),
    path('', include(router.urls)),
]

sevia_app/urls.py
from django.urls import path
from sevia_app import views
from sevia_app.api import views as api_views

app_name = 'sevia_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('users/', views.users, name='users'),
    path('facilities/', views.FacilityListView.as_view(), name='facility_list'),
    path('facility/', views.FacilityCreateView.as_view(), name='facility_create'),
    path('facility/update/<int:pk>/', views.FacilityUpdateView.as_view(), name='facility_update'),
    path('facility/delete/<int:pk>/', views.FacilityDeleteView.as_view(), name='facility_delete'),
    path('facility/detail/<int:pk>/', views.FacilityDetailView.as_view(), name='facility_detail'),
    path('patients/', views.PatientListView.as_view(), name='patient_list'),
    path('patient', views.PatientCreateView.as_view(), name='patient_create'),
    path('patient/update/<int:pk>/', views.PatientUpdateView.as_view(), name='patient_update'),
    path('patient/delete/<int:pk>/', views.PatientDeleteView.as_view(), name='patient_delete'),
    path('patient/detail/<int:pk>/', views.PatientDetailView.as_view(), name='patient_detail'),
    path('countries/', views.CountryListView.as_view(), name='country_list'),
    path('country', views.CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', views.CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', views.CountryDeleteView.as_view(), name='country_delete'),
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('region/', views.RegionCreateView.as_view(), name='region_create'),
    path('region/update/<int:pk>/', views.RegionUpdateView.as_view(), name='region_update'),
    path('region/delete/<int:pk>/', views.RegionDeleteView.as_view(), name='region_delete'),
    path('districts/', views.DistrictListView.as_view(), name='district_list'),
    path('district/', views.DistrictCreateView.as_view(), name='district_create'),
    path('district/update/<int:pk>/', views.DistrictUpdateView.as_view(), name='district_update'),
    path('district/delete/<int:pk>/', views.DistrictDeleteView.as_view(), name='district_delete'),
    path('patient_datas/', views.PatientDataListView.as_view(), name='patient_data_list'),
    path('patient_data/', views.PatientDataCreateView.as_view(), name='patient_data_create'),
    path('patient_data/update/<slug:pk>/', views.PatientDataUpdateView.as_view(), name='patient_data_update'),
    path('patient_data/delete/<slug:pk>/', views.PatientDataDeleteView.as_view(), name='patient_data_delete'),
    path('reviewer_datas/', views.ReviewerDataListView.as_view(), name='reviewer_data_list'),
    path('reviewer_data/<slug:patient_data_uri>', views.ReviewerDataCreateView.as_view(), name='reviewer_data_create'),
    path('reviewer_data/update/<slug:pk>/', views.ReviewerDataUpdateView.as_view(), name='reviewer_data_update'),
    path('reviewer_data/delete/<slug:pk>/', views.ReviewerDataDeleteView.as_view(), name='reviewer_data_delete'),
    path('settings/', views.settings, name='settings'),
    path('report/', views.ReportView.as_view(), name='reports'),
    path('api/app-dashboard', api_views.app_dash, name='app-dash'),
]

sevia_app/models.py
from django.db import models
from accounts.models import User
import datetime
from django.utils.translation import ugettext_lazy as _
import uuid
from django.contrib.auth.models import Group
from django.contrib.postgres.fields import JSONField


ASSESSMENT_CHOICES = [
        ('VIA neg','VIA Negative No treatment'),
        ('VIA+ for cryotherapy','VIA Positive for cryotherapy/Thermal Cagulation'),
        ('VIA+ LEEP','VIA Positive LEEP'),
        ('VIA+ refer LEEP','VIA Positive Refer ForLEEP'),
        ('Suspect Cancer','Suspect For Cancer Take Punch Biopsy'),
        ('Cervicitis Give Antibiotics','Cervicitis Give Antibiotics'),
        ('Cervical Polyp','Cervical Polyp (Refer / Do Polypectomy)'),
        ('Others','Others')
        ]

class Country(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)

    class Meta:
        verbose_name_plural = "Countries"
    
    def __str__(self):
        return self.name

class Region(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)
    country = models.ForeignKey(Country,on_delete=models.PROTECT,)

    
    def __str__(self):
        return self.name

class District(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, blank=True)
    region = models.ForeignKey(Region,on_delete=models.PROTECT,)

    
    def __str__(self):
        return self.name

class FacilityGroupDetail(models.Model):
    id = models.AutoField(primary_key=True)
    group_name = models.CharField(max_length=100, blank=True)
    users = models.ManyToManyField(User)
    def __str__(self):
        return self.group_name

class Facility(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=30, blank=True,null=True)
    district = models.ForeignKey(District,on_delete=models.PROTECT,)
    facility_group = models.ForeignKey(FacilityGroupDetail,on_delete=models.PROTECT,)
    name = models.CharField(max_length=60, blank=True)
    phone = models.CharField(max_length=60, null=True,blank=True)
    users = models.ManyToManyField(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        verbose_name_plural = "Facilities"
    
    def __str__(self):
        return self.name

    def get_full_address(self):
        return self.district.name + ' , ' + self.district.region.name



class Form(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField(null=True,blank=True,default=None)
    country_id = models.ForeignKey(Country, on_delete=models.PROTECT,null=True,blank=True)
    group = models.ForeignKey(Group,on_delete=models.PROTECT,null=True,blank=True,default=None)
    table_name = models.CharField(max_length=30)
    table_def = models.TextField(null=True,blank=True,default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.table_name

class FormData(models.Model):
    uri = models.CharField(primary_key=True,max_length=64,default=uuid.uuid4)
    form_id = models.ForeignKey(Form,on_delete=models.PROTECT,)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT,)
    exported = models.BooleanField(default=0)
    exported_at = models.DateTimeField(blank=True,default=None,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    data = JSONField(null=True)

    def __str__(self):
        return self.uri

class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(verbose_name='First Name',max_length=30,blank=True,null=True,default=None)
    middle_name = models.CharField(verbose_name='Middle Name',max_length=30,blank=True,null=True,default=None)
    last_name = models.CharField(verbose_name='Sur Name',max_length=30,blank=True,null=True,default=None)
    phone = models.CharField(verbose_name='phonenumber',max_length=30,null=True, blank=True)
    age = models.CharField(verbose_name='age',max_length=30,null=True, blank=True)
    facility = models.ManyToManyField(Facility)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,null=True, blank=True)

    def __str__(self):
        return str(self.id)

    def get_full_name(self):
        first_name = self.first_name if self.first_name else '' 
        middle_name = self.middle_name if self.middle_name else '' 
        last_name = self.last_name if self.last_name else '' 
        fullname = self.first_name + ' ' + middle_name +' ' + last_name
        return str(fullname)


class FormPatientDataV1(models.Model):

    PITC_CHOICES = [('No','No'),('Yes','Yes')]
    HIV_CHOICES = [('Positive','Positive'),('Negative','Negative'),('Unknown','Unknown')]
    VISIT_CHOICES = [
        ('New client (nevwer been screened)','New client (nevwer been screened)'),
        ('Postponed cryotherapy','Postponed cryotherapy'),
        ('Post-treatment complication (Cryo or LEEP)','Post-treatment complication (Cryo or LEEP)'),
        ('LEEP','LEEP'),
        ('1 year follow-up VIA+ (VIA+ treated with Cryo or LEEP)','1 year follow-up VIA+ (VIA+ treated with Cryo or LEEP)'),
        ('Routine VIA screening (returning client previously VIA-)','Routine VIA screening (returning client previously VIA-)'),
        ('Referred for VIA+ client(reffered for cryo)','Referred for VIA+ client(reffered for cryo)'),
        ('Referred for suspect cancer','Referred for suspect cancer'),
        ('Post-cryotherapy images','Post-cryotherapy images'),
        ]
    

    uri = models.CharField(max_length=64,primary_key=True,unique=True,default=uuid.uuid4)
    patient = models.ForeignKey(Patient,on_delete=models.PROTECT,)
    provider = models.ForeignKey(User,on_delete=models.PROTECT,related_name="provider")
    ccs_providers_full_name = models.CharField(max_length=128,blank=True, null=True)
    ccs_providers_phone_no = models.CharField(max_length=128,blank=True, null=True)
    screen_date = models.DateField(default=datetime.date.today)
    parity = models.BigIntegerField(blank=True, null=True)
    patient_received_pitc = models.CharField(max_length=128,default=None,blank=True, null=True,choices=PITC_CHOICES,)
    ccs_facility_no = models.CharField(max_length=128,blank=True, null=True)
    ccs_no = models.CharField(max_length=128,blank=True, null=True)
    hiv_status = models.CharField(max_length=128,default=None,blank=True, null=True,choices=HIV_CHOICES,)
    assessment = models.CharField(max_length=128,default=None,blank=True, null=True,choices=ASSESSMENT_CHOICES,)
    visit_status = models.CharField(max_length=128,default=None,blank=True, null=True, choices=VISIT_CHOICES,)
    photo_1 = models.ImageField(upload_to='patient_data/%Y/%m/%d',blank=True, null=True)
    photo_2 = models.ImageField(upload_to='patient_data/%Y/%m/%d', blank=True, null=True)
    photo_3 = models.ImageField(upload_to='patient_data/%Y/%m/%d', blank=True, null=True)
    form_version = models.CharField(max_length=128,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.uri)

    class Meta:
        # managed = False
        db_table = '_form_patient_data_v1'

class FormReviewerDataV1(models.Model):
    uri = models.CharField(max_length=64,primary_key=True,default=uuid.uuid4)
    patient_data = models.OneToOneField(FormPatientDataV1, to_field="uri",on_delete=models.PROTECT,related_name="reviewer_data",db_constraint=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name="creator",db_constraint=False)
    assessment = models.CharField(max_length=128, blank=True, null=True,choices=ASSESSMENT_CHOICES,)
    comment = models.CharField(max_length=128, blank=True, null=True)
    mismatch = models.IntegerField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


    def __str__(self):
        return str(self.uri)
        
    class Meta:
        # managed = False
        db_table = '_form_reviewer_data_v1'


class DataDictionary(models.Model):
    formId = models.TextField(null=True,blank=True,default=None)
    formVersion = models.TextField(null=True,blank=True,default=None)
    variableKey= models.TextField(null=True,blank=True,default=None)
    variableName = models.TextField(null=True,blank=True,default=None)
    description = models.TextField(null=True,blank=True,default=None)
    status = models.IntegerField(blank=True, null=True,default=0)

    
    def __str__(self):
        return self.formId

class FormPatientDataV2(models.Model):

    HIV_CHOICES = [('Positive','Positive'),('Negative','Negative'),('Unknown','Unknown')]
    
    uri = models.CharField(max_length=64,primary_key=True,unique=True,default=uuid.uuid4)
    patient = models.ForeignKey(Patient,on_delete=models.PROTECT,)
    provider = models.ForeignKey(User,on_delete=models.PROTECT)
    visit_date = models.DateField(default=datetime.date.today)
    visit_status = models.CharField(max_length=128,default=None,blank=True, null=True)
    first_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    middle_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    last_initial = models.CharField(max_length=30,blank=True,null=True,default=None)
    phone = models.CharField(max_length=30,blank=True,null=True,default=None)
    age = models.IntegerField(blank=True, null=True)
    passport = models.CharField(max_length=30,blank=True,null=True,default=None)
    followup_reasons = models.CharField(max_length=128,default=None,blank=True, null=True)

sevia_app/templates/sevia_app/district_delete_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="post">{% csrf_token %}
         <legend class="border-bottom mb-4">Delete District</legend>
            <p>Are you sure you want to delete district with id <b>"{{ object }}"</b> ?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'sevia_app:facility_list' %}" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
{% endblock content %}

sevia_app/templates/sevia_app/district_list.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>Districts</h1>
<div class="card">
  <div class="card-body">
    <table class="table table-striped table-bordered" id="facilities_table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Region</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {%for district in district_list %}
        <tr>
          <th scope="row">{{ district.id}}</th>
          <td>{{ district.name}}</td>
          <td>{{ district.region.name}}</td>
          <td>
            <a
              role="button"
              href="{% url 'sevia_app:district_update' district.id %}"
              class="btn btn-pure btn-primary icon md-edit"
            ></a>
            <a
              role="button"
              href="{% url 'sevia_app:district_delete' district.id %}"
              class="btn btn-pure btn-danger icon md-delete"
            ></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>

{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>

<script language="javascript">
  $(document).ready(function () {
    $("#facilities_table").DataTable({
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

sevia_app/templates/sevia_app/district_update_form.html
{% extends "sevia_app/base.html" %} {% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 500px">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update District</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
          <a
            href="{% url 'sevia_app:district_list' %}"
            class="btn btn-outline-info"
            >Cancel</a
          >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

{% endblock extra_styles %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script language="javascript">
  $(document).ready(function () {
    $(".selectmultiple , .select").select2();
  });
</script>

{% endblock extra_js %}

sevia_app/templates/sevia_app/facility_delete_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="post">{% csrf_token %}
         <legend class="border-bottom mb-4">Delete Facility</legend>
            <p>Are you sure you want to delete <b>"{{ object }}"</b> ?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'sevia_app:facility_list' %}" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
{% endblock content %}

sevia_app/templates/sevia_app/facility_list.html
{% extends "sevia_app/base.html" %} {% load static %} {% block content %}
<h1>Facilities</h1>
<div class="card">
  <div class="card-body">
    <table class="table table-striped table-bordered" id="facilities_table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">District</th>
          <th scope="col">Region</th>
          <th scope="col">Phone</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {%for facility in facility_list %}
        <tr>
          <th scope="row">{{facility.id}}</th>
          <td>{{facility.name}}</td>
          <td>{{facility.district.name}}</td>
          <td>{{facility.district.region.name}}</td>
          <td>{{facility.phone}}</td>
          <td>
            <a
              role="button"
              href="{% url 'sevia_app:facility_update' facility.id %}"
              class="btn btn-pure btn-primary icon md-edit"
            ></a>
            <a
              role="button"
              href="{% url 'sevia_app:facility_detail' facility.id %}"
              class="btn btn-pure btn-primary icon md-chart"
            ></a>
            <a
              role="button"
              href="{% url 'sevia_app:facility_delete' facility.id %}"
              class="btn btn-pure btn-danger icon md-delete"
            ></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  rel="stylesheet"
  href="{% static 'sevia_app/global/vendor/datatables.net-bs4/dataTables.bootstrap4.css' %}"
/>
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/fixedheader/3.1.8/css/fixedHeader.bootstrap.min.css"
/>
<style>
  div.dataTables_wrapper {
        margin: 0 auto;
    }
    thead input {
        width: 100%;
    }
    td {
        width: 1000px;
    }

    table{
  margin: 0 auto;
  width: 100%;
  clear: both;
  border-collapse: collapse;
  table-layout: fixed; 
  word-wrap:break-word;
}
</style>

{% endblock extra_styles %} {% block extra_js %}

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.8/js/dataTables.fixedHeader.min.js"></script>

<script language="javascript">
  $(document).ready(function () {
    $("#facilities_table").DataTable({
      scrollX: true,
      fixedHeader: true,
      language: {
        lengthMenu: "_MENU_",
      },
    });
  });
</script>

{% endblock extra_js %}

sevia_app/templates/sevia_app/facility_update_form.html
{% extends "sevia_app/base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <div class="card mx-auto" style="width: 500px">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update Facility</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
          <a
            href="{% url 'sevia_app:facility_list' %}"
            class="btn btn-outline-info"
            >Cancel</a
          >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extra_styles %}

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

{% endblock extra_styles %} {% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script language="javascript">
  $(document).ready(function () {
    $(".selectmultiple , .select").select2();
  });
</script>

{% endblock extra_js %}

sevia_app/templates/sevia_app/patient_delete_form.html
{% extends "sevia_app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="content-section">
        <form method="post">{% csrf_token %}
         <legend class="border-bottom mb-4">Delete Client</legend>
            <p>Are you sure you want to delete client with id <b>"{{ object }}"</b> ?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'sevia_app:facility_list' %}" class="btn btn-outline-info">Cancel</a>
        </form>
    </div>
{% endblock content %}

sevia_app/templates/sevia_app/profile.html
{% extends "sevia_app/base.html" %}
{% load static %}
{% load crispy_forms_tags %} 
{% block content %}
    <div class="row">
      <div class="col-lg-3">
        <!-- Page Widget -->
        <div class="card card-shadow text-center">
          <div class="card-block">
            <a class="avatar avatar-lg" href="javascript:void(0)">
              <img src="{% static 'sevia_app/global/portraits/profile_black.jpg' %}" alt="...">
            </a>
            <h4 class="profile-user">{{user.fullname}}</h4>
            <p class="profile-job">
              {%for g in user.groups.all %}
              {{g.name}} {% if not forloop.last %}, {% endif %}
            {%endfor%}</p>
          </div>
          <div class="card-footer">
            <div class="row no-space">
              <div class="col-6">
                <strong class="profile-stat-count">{{user.get_total_cases}}</strong>
                <span>Cases</span>
              </div>
              <div class="col-6">
                <strong class="profile-stat-count">{{user.facility_set.count}}</strong>
                <span>Facilities</span>
              </div>
            </div>
          </div>
        </div>
        <!-- End Page Widget -->
      </div>

      <div class="col-lg-9">
        <!-- Panel -->
        <div class="panel">
          <div class="panel-body nav-tabs-animate nav-tabs-horizontal" data-plugin="tabs">
            <ul class="nav nav-tabs nav-tabs-line" role="tablist">
              <li class="nav-item" role="presentation"><a class="active nav-link" data-toggle="tab" href="#activities"
                  aria-controls="activities" role="tab">Change Password</a></li>

            </ul>

            <div class="tab-content">
              <div class="tab-pane active animation-slide-left" id="activities" role="tabpanel">
                <form method="POST">
                  {% csrf_token %}
                <fieldset class="form-group mt-10">
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Change Password</button>
                </div>  
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- End Panel -->
      </div>
    </div>
{% endblock content %}

sevia_app/templates/sevia_app/users.html
{% extends "sevia_app/base.html" %}
{% block content %}
    <h1>Settings</h1>
{% endblock content %}